<?php
defined('_JEXEC') or die('Restricted access');

?>
<?php 
// join multiple .gedata from strt analysis [generated by strst2Qsingle.php]
// Rikard Erlandsson Nov 2011
// Reads single experiment Qlucore files and combines them
$rpmQfiles        = array();
$sampleCounts     = array();
$attributeCounts  = array();
$attributeNames   = array();
$attributes       = array();
$variableCounts   = array();
$annotationCounts = array();
$attributeLines   = array();
$beforeValues = 0;
  echo "<h1>Download of combined analysis results for Qlucore</h1>\n";
  $menus = &JSite::getMenu();
  $menu  = $menus->getActive();
  $itemid = $menu->id;

echo "The following files have been combined: <br /><br />\n";
$files = array();
foreach ($_POST as $params => $value) {
  if (strpos($params, "file") !== false) {
    array_push($files, $value);
    echo $value . "<br />\n";
  }
}

for ($i = 0; $i  < count($files); $i++) {
  $rpmfile = $files[$i];
  array_push($rpmQfiles, $rpmfile);
  // read in number of samples, attributes, variables and annotations in each RPM file
  $fh = fopen($rpmfile, 'r');
  $line = stream_get_line($fh, 100, "\n\n");
  $line = stream_get_line($fh, 100, "\n\n");
  preg_match_all('(\d+)', $line, $out);
  array_push($sampleCounts,    $out[0][0]);
  array_push($attributeCounts, $out[0][1]);  
  array_push($variableCounts,  $out[0][2]);
  array_push($annotationCounts, $out[0][3]);
  $attributes[$i]     = array();
  $attributeNames[$i] = array();
  $attributeLines[$i] = array();
  for ($ii = 0; $ii < $out[0][1]; $ii++) {  // $out[0][1] equals attribute count
    $line = stream_get_line($fh, 10000, "\n");
    array_push($attributes[$i], $line);
    $attributeValues = explode("\t", $line);
    array_push($attributeNames[$i], $attributeValues[$out[0][3]]); // names comes at column annotationcount
    $attributeLines[$i][$attributeValues[$out[0][3]]] = $line;
  }
  fclose($fh);
}

// print a summary
//    print "sampleCounts     " . count($sampleCounts) . " " . join("-", $sampleCounts) . "\n";
//    print "attributeCounts  " . count($attributeCounts) . " " . join("-", $attributeCounts) . "\n";
//    print "attributeNames   " . count($attributeNames) . " arrays\n";
//    for ($i = 0; $i  < count($attributeNames); $i++) {
//      print "                 :" . join(":", $attributeNames[$i]) . "\n";
//    }
//    print "variableCounts   " . count($variableCounts) . " " . join("-", $variableCounts) . " is 9 less since spikes are removed\n";
//    print "annotationCounts " . count($annotationCounts) . " " . join("-", $annotationCounts) . "\n";
//    print join("\n", $rpmQfiles) . "\n";

// join the different Qlucore files
$sampleCount = array_sum($sampleCounts);
$attributesArray = array();
for ($i = 0; $i < count($rpmQfiles); $i++) {
  foreach ($attributeNames[$i] as $attributeName) {
    if (!(array_key_exists($attributeName, $attributesArray))) {
      $attributesArray[$attributeName] = "attribute";
    }
  }
}
$attributeCount = count($attributesArray) + 1;
if (array_sum($variableCounts)/count($rpmQfiles) == $variableCounts[0]) {
  $variableCount = $variableCounts[0];
}
if (array_sum($annotationCounts)/count($rpmQfiles) == $annotationCounts[0]) {
  $variableAnnotationCount = $annotationCounts[0];
}

$fhs = array();
$tmpdir = "/srv/www/htdocs/joomla16/tmp";
$now = date("YmdHis");
$outFile = $now . "_Normalized.gedata";
$fh = fopen($tmpdir . "/" . $outFile, 'w') or die("Can't open file for writing");
// print header
fwrite($fh, "Qlucore\tgedata\tversion 1.0\n");
fwrite($fh, "\n");
fwrite($fh, "$sampleCount\tsamples\twith\t$attributeCount\tattributes\n");
fwrite($fh, "$variableCount\tvariables\twith\t$variableAnnotationCount\tannotations\n");
fwrite($fh, "\n");
$values = array();
for ($i = 0; $i < count($rpmQfiles); $i++) {
  $fhs[$i] = fopen($rpmQfiles[$i], 'r');
  $line = stream_get_line($fhs[$i], 100, "\n\n");
  $line = stream_get_line($fhs[$i], 100, "\n\n");
  $line = stream_get_line($fhs[$i], 10000, "\n");
  $attributeValues = explode("\t", $line);
  while ($attributeValues[$beforeValues] != "Sample") {
    $beforeValues++;
  }
  if ($i == 0) {
    fwrite($fh, $line);
  } else {
    $counter = 0;
    while ($counter <= $beforeValues) {
      array_shift($attributeValues);
      $counter++;
    }
    fwrite($fh, "\t" . join("\t", $attributeValues));
  }

}
fwrite($fh, "\n");
$counter = 0;
while ($counter < $beforeValues) {
  $counter++;
  fwrite($fh, "\t");
}
fwrite($fh, "AnalysisFolder");
for ($i = 0; $i < count($rpmQfiles); $i++) {
  $folders = explode("/", $rpmQfiles[$i]);
  for ($ii = 1; $ii <= $sampleCounts[$i]; $ii++) {
    fwrite($fh, "\t" . $folders[4]);
  }
}
fwrite($fh, "\n");

// print the rest of the attribute lines
foreach ($attributesArray as $attributeName => $a0) {
  if ($attributeName != "Sample") {
    $counter = 0;
    while ($counter < $beforeValues) {
      $counter++;
      fwrite($fh, "\t");
    }
    fwrite($fh, $attributeName);
    for ($i = 0; $i < count($rpmQfiles); $i++) {
      if (array_key_exists($attributeName, $attributeLines[$i])) {
        $attVals = explode("\t", $attributeLines[$i][$attributeName]);
        $counter = 0;
        while ($counter <= $beforeValues) {
          array_shift($attVals);
          $counter++;
        }
        fwrite($fh, "\t" . join("\t", $attVals));
      } else {
        for ($ii = 1; $ii <= $sampleCounts[$i]; $ii++) {
          fwrite($fh, "\t");
        }
      }
    }
    fwrite($fh, "\n");
  }  
}
fwrite($fh, "Feature\tChr\tPos\tStrand\tTrLen\n");

for ($i = 0; $i < count($rpmQfiles); $i++) {
  $line = "";
  while (strpos($line, "Feature") === false) {
    $line = stream_get_line($fhs[$i], 10000, "\n");
  }
}

while (!(feof($fhs[0]))) {
  for ($i = 0; $i < count($rpmQfiles); $i++) {
    $line = stream_get_line($fhs[$i], 10000, "\n");
    if ($i == 0) {
      fwrite($fh, $line);
    } else {
      $reads = array();
      $reads = explode("\t", $line);
      $counter = 0;
      while ($counter < $beforeValues) {
        array_shift($reads);
        $counter++;
      }
      fwrite($fh, join("\t", $reads));
    }
  }
  fwrite($fh, "\n");  
}

fclose($fh);
echo "<br /><br />Right-click this link to save the output file on your computer:<br /><br />\n";
echo "<a href=http://192.168.1.12/joomla16/tmp/$outFile >$outFile</a>\n";

?>
